// t()는 main.cjs 최상단의 i18n require에서 공유(재require 금지 — src/content/locale/i18n.cjs 헤더 주석 참조)
// ★Phase 0 Step 3a: base/mult/chainMul 훅(11부적) + ★3b: settle/settleOverride 훅(13부적) = 부적 선언 1곳
//   (effect-registry, 로드맵 §2). hooks.base(card,ctx)->number / hooks.mult(card,left,ctx)->number /
//   hooks.chainMul(bonus,runLen,ctx)->number / hooks.settle(row,hk,ctx)->number(가산) /
//   hooks.settleOverride(row,hk,ctx)->number|null(hb 자체를 덮어씀, broker 전용). 엔진은 src/rules/scoring.cjs.
const CHARMS=[
  {id:"greed",  name:t('charm.greed.name'),   desc:t('charm.greed.desc'),
    hooks:{ base:(card,ctx)=>3 }},
  {id:"pyro",   name:t('charm.pyro.name'),   desc:t('charm.pyro.desc'),
    hooks:{ mult:(card,left,ctx)=> ctx.isRed(card.suit) ? 2 : 0 }},
  {id:"suited", name:t('charm.suited.name'),desc:t('charm.suited.desc'),
    hooks:{ mult:(card,left,ctx)=> card.suit===left.suit ? 1 : 0 }},
  {id:"runner", name:t('charm.runner.name'),   desc:t('charm.runner.desc'),
    hooks:{ mult:(card,left,ctx)=> Math.abs(card.rank-left.rank)===1 ? 1 : 0 }},
  {id:"jackpot",name:t('charm.jackpot.name'),   desc:t('charm.jackpot.desc'),
    hooks:{ chainMul:(bonus,runLen,ctx)=> runLen>=4 ? bonus*2 : bonus }},
  {id:"noir",     name:t('charm.noir.name'),   desc:t('charm.noir.desc'),
    hooks:{ mult:(card,left,ctx)=> !ctx.isRed(card.suit) ? 2 : 0 }},
  {id:"broker",   name:t('charm.broker.name'), desc:t('charm.broker.desc'),
    hooks:{ settleOverride:(row,hk,ctx)=>{ const BR={pair:.05,twoPair:.08,trips:.12}; return BR[hk]!=null ? Math.round(ctx.blindBase*BR[hk]) : null; } }},
  {id:"twins",    name:t('charm.twins.name'), desc:t('charm.twins.desc'),
    hooks:{ settle:(row,hk,ctx)=>{ const rc={}; for(const c of row) if(c.enh!=="wild") rc[c.rank]=(rc[c.rank]||0)+1; let g=0; for(const k in rc) if(rc[k]>=2) g++; return Math.round(ctx.blindBase*.03*Math.min(g,4)); } }},
  {id:"compactor",name:t('charm.compactor.name'), desc:t('charm.compactor.desc'),
    hooks:{ base:(card,ctx)=> Math.min(8, Math.max(0, 32-ctx.liveDeckCount)) }},
  {id:"runts",    name:t('charm.runts.name'), desc:t('charm.runts.desc'),
    hooks:{ base:(card,ctx)=> card.rank<=3 ? 4 : 0 }},
  {id:"bridge",   name:t('charm.bridge.name'),   desc:t('charm.bridge.desc'),
    hooks:{ settle:(row,hk,ctx)=> Math.round(ctx.blindBase*.03*Math.min(ctx.bridgeCount(row),3)) }},
  {id:"stair",    name:t('charm.stair.name'),desc:t('charm.stair.desc'),
    hooks:{ settle:(row,hk,ctx)=> Math.round(ctx.blindBase*.04*Math.max(0,Math.min(ctx.maxAscLen(row),6)-2)) }},
  {id:"keystone", name:t('charm.keystone.name'), desc:t('charm.keystone.desc'),
    hooks:{ settle:(row,hk,ctx)=> Math.round(ctx.blindBase*.18*Math.max(0,(ctx.edgeVal(row)-12)/12)) }},
  {id:"lapidary", name:t('charm.lapidary.name'), desc:t('charm.lapidary.desc'), cost:5, cluster:"gem",
    hooks:{ base:(card,ctx)=> (card.enh && !ctx.boss('rust')) ? 3 : 0 }},
  {id:"prism",    name:t('charm.prism.name'),    desc:t('charm.prism.desc'), cost:5, cluster:"gem",
    hooks:{ settle:(row,hk,ctx)=>{ let w=0,g=0,m=0; for(const c of row){ if(c.enh==="wild")w=1; else if(c.enh==="gold")g=1; else if(c.enh==="mult")m=1; } return (w&&g&&m && !ctx.boss('rust')) ? Math.round(ctx.blindBase*.12) : 0; } }},
  {id:"jewelbox", name:t('charm.jewelbox.name'), desc:t('charm.jewelbox.desc'), cluster:"gem",
    hooks:{ settle:(row,hk,ctx)=>{ let e=0; for(const c of row) if(c.enh) e++; return Math.round(ctx.blindBase*.025*Math.min(e,6)); } }},
  {id:"highmult", name:t('charm.highmult.name'), desc:t('charm.highmult.desc'), cost:5, cluster:"apex",
    hooks:{ mult:(card,left,ctx)=> card.rank>=7 ? 1 : 0 }},
  {id:"magnate",  name:t('charm.magnate.name'),  desc:t('charm.magnate.desc'), cluster:"apex",
    hooks:{ settle:(row,hk,ctx)=>{ let h=0; for(const c of row) if(c.enh!=="wild"&&c.rank>=7) h++; return Math.round(ctx.blindBase*.03*Math.min(h,5)); } }},
  {id:"echo",   name:t('charm.echo.name'),   desc:t('charm.echo.desc'), cost:3, cluster:"cartel",
    hooks:{ mult:(card,left,ctx)=> card.rank===left.rank ? 1 : 0 }},
  {id:"loaded", name:t('charm.loaded.name'), desc:t('charm.loaded.desc'), cluster:"cartel",
    hooks:{ settle:(row,hk,ctx)=> hk==="fourKind" ? Math.round(ctx.blindBase*.10) : hk==="fiveKind" ? Math.round(ctx.blindBase*.30) : 0 }},
  {id:"climax", name:t('charm.climax.name'),   desc:t('charm.climax.desc'), cluster:"cartel",
    hooks:{ settle:(row,hk,ctx)=>{ if(!["fullHouse","fourKind","straightFlush","fiveKind"].includes(hk)) return 0; let L=1,cur=1; for(let i=1;i<row.length;i++){ if(ctx.connect(row[i],row[i-1])){ cur++; if(cur>L)L=cur; } else cur=1; } return Math.round(ctx.blindBase*.03*Math.max(0,Math.min(L,8)-5)); } }},
  {id:"evenodd",   name:t('charm.evenodd.name'), desc:t('charm.evenodd.desc'), cluster:"parity",
    hooks:{ settle:(row,hk,ctx)=>{ let ev=0,od=0; for(const c of row) if(c.enh!=="wild")(c.rank%2?od++:ev++); return Math.round(ctx.blindBase*.04*Math.max(0,Math.max(ev,od)-5)); } }},
  {id:"paritybet", name:t('charm.paritybet.name'), desc:t('charm.paritybet.desc'), cluster:"parity",
    hooks:{ settle:(row,hk,ctx)=>{ const nw=row.filter(c=>c.enh!=="wild"); return (row.length>=8 && (nw.every(c=>c.rank%2===0)||nw.every(c=>c.rank%2===1))) ? Math.round(ctx.blindBase*.30) : 0; } }},
  {id:"twotone",  name:t('charm.twotone.name'), desc:t('charm.twotone.desc'),
    hooks:{ settle:(row,hk,ctx)=>{ let h=0,d=0,s=0,c=0; for(const x of row){ if(x.enh==="wild")continue; if(x.suit===1)h++; else if(x.suit===2)d++; else if(x.suit===0)s++; else c++; } const red=h+d,black=s+c,dom=Math.max(red,black); const bothSuits=red>=black?(h>0&&d>0):(s>0&&c>0); return bothSuits ? Math.round(ctx.blindBase*0.04*Math.max(0,Math.min(dom,8)-4)) : 0; } }},
];
module.exports = { CHARMS };
